### ISSUE TITLE
弹幕文字在全屏下使用 transform 缩放导致文字渲染模糊

### ISSUE THREAD

**Issue by lixiaoyan** [Zhuogu/bilibili-helper#10]
正常情况:
![text-normal](https://cloud.githubusercontent.com/assets/1610614/4695994/b7b31f72-5847-11e4-9b29-7ff811f73621.png)

全屏:
![text-fullscreen](https://cloud.githubusercontent.com/assets/1610614/4695995/c1e990c0-5847-11e4-883e-cd359bed1337.png)

**Comment by jabbany** [comment]
刚才突然发现，这个现象还真只有在Chrome下才发生。应该是Chrome 对待 transform:scale 和对待 zoom 不同，transform:scale 会导致GPU拉伸图层产生像素化的状况， 而不会考虑到大部分字体其实是矢量图。

参考Firefox下同样的显示效果：
![screenshot from 2015-04-16 03 33 39](https://cloud.githubusercontent.com/assets/821034/7176134/83d9691c-e3e9-11e4-8941-a2ca981455db.png)
对比 Chrome：
![screenshot from 2015-04-16 03 33 42](https://cloud.githubusercontent.com/assets/821034/7176139/91d52272-e3e9-11e4-8768-131ccb1eef65.png)

或许可以考虑在Chrome下改成采用非标准的 zoom 来实现同步缩放。
