### ISSUE TITLE
【bug】关于优酷播放器替换失败的bug反馈

### ISSUE THREAD

**Issue by ru8lq0005** [Zhuogu/bilibili-helper#11]
不知道是什么原因导致的，在看新番http://www.bilibili.com/video/av1642240/index_2.html   的时候，播放器替换成功之后页面闪了一下立刻又变回了优酷播放器，但是其他优酷源的新番（斩·赤红之瞳，日常异能等）及视频（暴走大事件等...）正常...0.6.8之前的插件会出现不和谐页面，0.6.8出现闪退回原有播放器，手动切换swf和iframe框架都不行，不知原因为何，我的浏览器是chrome37和360急速8.0（37的内核）。希望能够查清原因。
本来想附图的...不知道为啥上传不了图片..
PS.感谢咕咕大大，辛苦了~

**Comment by Zhuogu** [comment]
目前只能替换可以通过 B 站官方 API 获取到的视频内容.
