### ISSUE TITLE
能否增加弹幕字体和字号的设定

### ISSUE THREAD

**Issue by be5invis** [Zhuogu/bilibili-helper#16]
全屏下太大了

**Comment by swordfeng** [comment]
手工改css（笑）
其实。。。因为作者长期未上线，本人正在自撸播放器中。。。

**Comment by be5invis** [comment]
解包插件去改么

- 发送自我的Sony Xperia™智能手机

---- Jianfeng Zhang 编写 ----

手工改css（笑）
其实。。。因为作者长期未上线，本人正在自撸播放器中。。。

---

**Comment by Zhuogu** [comment]
@swordfeng fork 出去改，改完了发 merge request 上来

**Comment by swordfeng** [comment]
作者菌上线了
我现在直接在ABPlayer上面改，不过他的源代码基本上被我翻新了一遍，很多内容都重写了……现在我改成了视频播放列表会被连续播放，共用同一个弹幕文件（因为B站和各大视频站还是有不少视频是有分割的）就是好像CoreCommentLibrary被我改的不工作了（笑）还在研究中
另外，本人UI苦手。。。问个问题，这个助手的播放按钮之类的都是用css设置:before节点的content，其原理是啥？在其它地方我不能重现。。。

**Comment by Zhuogu** [comment]
@swordfeng 抱歉, 又人口失踪了好长一段时间. 用 :before 和 :after 是因为懒得再去改 DOM 了, 其实是比较 hack 的方法, 盖在原 element 上.

**Comment by swordfeng** [comment]
@Zhuogu 嗯，我成功使用类似方法了，只是在chrome下看起来怪怪的（笑）
我记得（上次）使用你的播放器的时候发现font-weight设置太重了……
是否重复放大的问题，abplayerhtml5里本来有这个设置的样子

**Comment by Zhuogu** [comment]
Fixed in release v0.7.0.
