### ISSUE TITLE
[FEATURE REQUEST]能否增加firefox的支持？

### ISSUE THREAD

**Issue by adam900710** [Zhuogu/bilibili-helper#19]

**Comment by swordfeng** [comment]
我觉得作者应该写成userscript而不是extension，那样很容易就能实现在不同浏览器上运行了

**Comment by adam900710** [comment]
其实我最想要的功能就只是HTML5播放器。。。。

不止为啥我这里网络用B站flash播放器一直卡在加载视频，只有用html5的才能播放。。。
不知道是啥原因。。。

2015-02-17 9:10 GMT+08:00 Jianfeng Zhang <notifications@github.com>:

**Comment by swordfeng** [comment]
@adam900710
所以我写了一个。。。请看我的bilicake，这就是个替换成html5播放器的实现。。。最近改了一下判断，只有vupload源会自动替换，而且播放器现在还有很多问题。。。播放器源码看我fork的ABPlayerHTML5，与原播放器对比修改了很多东西，欢迎pr。。。

**Comment by adam900710** [comment]
我这里不能放的全是优酷源。。。。
其实bilibili helper的这个player我感觉就够用了，反正也不发弹幕。。。

**Comment by Zhuogu** [comment]
目前没有相关计划, 欢迎 fork 自行移植, 先关了.
