### ISSUE TITLE
搜狐源的解析会出现 undefined

### ISSUE THREAD

**Issue by typcn** [Zhuogu/bilibili-helper#22]
Error in event handler for (unknown): TypeError: Cannot read property 'url' of undefined
    at chrome-extension://kpbnombpnpcffllnianjibmpadjolanh/bilibili_injected.js:1:6265

**Comment by Zhuogu** [comment]
麻烦提供一个样例视频地址, 谢谢.

**Comment by typcn** [comment]
b站api返回无法支持，代码里直接读取了durl然后失败了，貌似不好解决

**Comment by Zhuogu** [comment]
那我对这种情况加一个判断吧, 虽然不能获取地址但是比直接抛错误出来好.
