### ISSUE TITLE
bilibili helper 会修改网页字体

### ISSUE THREAD

**Issue by enerai** [Zhuogu/bilibili-helper#24]
系统是 Mac OSX 10.10，Chrome 是最新的稳定版，在开启 bilibili-helper 之后，B 站字体发生了变化，这是怎么回事呢？不想字体发生变化啊。应该怎么做呢？

**Comment by enerai** [comment]
如何能只开启替换播放器的功能呢？修改后的样式感觉没有原来的合适

**Comment by enerai** [comment]
或者用 ublock 添加一个什么样子的规则可以把扩展加载的 css 代码去掉呢？

**Comment by Zhuogu** [comment]
为什么用 OS X 不喜欢 Helvetica 而要用微软雅黑 _(:3」∠)_
我下一个版本加入这个选项吧.

**Comment by enerai** [comment]
谢谢啊！期待下个版本的更新。

主要因为替换字体之后，字体会整个小一圈，而且会有上移的现象，比如这个页面（http://www.bilibili.com/video/av2173008/），最上面的 z_top 区域字体上移情况明显，其他区域字体变小情况也比较明显。
