### ISSUE TITLE
在带参数的页面当中不能自动替换播放器

### ISSUE THREAD

**Issue by enerai** [Zhuogu/bilibili-helper#25]
反馈问题：当访问带参数页面的时候，插件不能自动替换播放器；去掉参数之后，播放器正常更换。

测试网址：
http://www.bilibili.com/video/av2154875/?tg
http://www.bilibili.com/video/av2184657/?br

**Comment by jabbany** [comment]
这个目测是绑定URL的时候太严格了，在这个[正则](https://github.com/Zhuogu/bilibili-helper/blob/master/bilibili_injected.js#L300) 里面

**Comment by Zhuogu** [comment]
Resolved with a6ab38963beb8aab978b7c428a5582cb637d1abe
